# Generated by Django 5.2.5 on 2026-08-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_city_movie_genre_movie_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='theater',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
