# Generated by Django 5.2.5 on 2026-08-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_theater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='theater',
        ),
    ]
