# Generated by Django 5.2.5 on 2026-08-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_booking_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='screen',
            field=models.CharField(default='Screen 1', max_length=100),
        ),
    ]
