# Generated by Django 5.2.5 on 2026-09-20 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_payment_refund_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booked_at'], name='movies_book_booked__a7ab7e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'booked_at'], name='movies_book_status_40a788_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['movie', 'status', 'booked_at'], name='movies_book_movie_i_3e8a9b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['theater', 'status', 'booked_at'], name='movies_book_theater_051445_idx'),
        ),
    ]
