# Generated by Django 5.2.5 on 2026-09-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_booking_movies_book_booked__a7ab7e_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='movies_paym_status_8acdf7_idx'),
        ),
    ]
