# Generated by Django 5.2.5 on 2026-09-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_payment_movies_paym_status_8acdf7_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movieposter',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
